apiVersion: apps/v1
kind: Deployment
metadata:
  name: algo-test-api-deployment
  labels:
    app: algo-test-api
    tier: backend
    name: algo-test
    instance: algo-test-api
    version: "1.0.0"
    component: api-server
    part-of: algo-test
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: REPLICA_COUNT
  selector:
    matchLabels:
      app: algo-test-api
  template: 
    metadata:
      name: algo-test-api-pod
      labels:
        app: algo-test-api
        tier: backend        
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - algo-test-api
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      nodeSelector:
        eks.amazonaws.com/nodegroup: facctum-application
      containers:
        - name: algo-test-api-container
          image: 381305464391.dkr.ecr.ap-south-1.amazonaws.com/algo-test/api:RELEASE_VERSION
          imagePullPolicy: Always
          ports:
            - name: main-port 
              containerPort: 3001
          envFrom:
          - configMapRef:
              name: algo-test-api-config
          resources:
            requests:
              cpu: "100m"
              memory: 128Mi
            limits:
              cpu: "500m"
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: main-port
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: main-port
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: main-port
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler 
metadata: 
  name: algo-test-api-deployment-hpa
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: algo-test-api-deployment
  minReplicas: 1 
  maxReplicas: 3 
  targetCPUUtilizationPercentage: 70
